"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def main():
    lim = 4000000
    first,second, next = 1,2,0
    sum = 2

    while next < lim:
        next = first + second
        first = second
        second = next
        if next%2 == 0:
            sum += next
    print "sum of all even-valued fibonacci numbers is %d"%sum

if __name__ == "__main__":
    main()
